# Generated by Django 4.1.3 on 2022-12-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nairapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default='1993-03-22'),
            preserve_default=False,
        ),
    ]
